[package]
authors = ["nc <mynameisnikitablack@gmail.com>"]
edition = "2021"
name = "vulkan_utils"
version = "0.1.0"

[dependencies]
ash = "0.37.0"
gpu-allocator = "0.20.0"
log = "0.4"
scopeguard = "1.1.0"
