[package]
authors = ["nc <mynameisnikitablack@gmail.com>"]
edition = "2018"
name = "vulkan_utils"
version = "0.1.0"

[dependencies]
ash = "0.33.3"
#ash-window = "0.7.0"
log = "0.4"
scopeguard = "1.1.0"
#winit = "0.25.0"
